config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home/about' => 'homes#about', as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  
  validates :name, uniqueness: true
  validates :name,length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}




  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :sign_up, :sign_in]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_outpathfor(resource)
     @user = User.new(user_params)
    @user.save
      flash[:notice] = "Signed out successfully."
    redirect_to root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :correct_user, only: [:edit, :update]
   
  def new
    @book = Book.new
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book_new.id)
    else
      @user = current_user
      @book = Book.all
      render :index
    end
  end

  def index
    @book_new = Book.new
    @book = Book.all
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to  book_path(@book.id)
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if@book.save
    flash[:notice] = "You have update book successfully."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end 

def about
end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new(user_params)
    @user.save
      flash[:notice] = "Welcome! You have signed up successfully."
    redirect_to user_path(current_user.id)
  end

  def create
    @user = User.new(user_params)
    if@user.save
      flash[:notice] = "Signed in successfully."
      redirect_to users_path(current.id)
    else
      redirect_to books_path
    end
  end

  def index
    @users = User.all
    @book_new = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to  user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if@user.save
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path
    else
      render :edit
    end
  end


private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h1>New book</h1>
<%= form_with model: book do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>


<p>Title</p>
<%= f.text_field :title %>

<p>Opinion</p>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<main>
<% if @book_new.errors.any? %>
  <%= @book_new.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book_new.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/user', user: @user %>
        <%= render 'book', book: @book_new %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>title</th>
              <th>opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @book.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.get_profile_image(100, 100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<%= render 'users/user', user: @user %>
<%= render 'book', book: @book_ %>

<%= form_with model: @book do |f| %>

<%= f.text_field :title %>
<%= f.text_area :body %>

<%= f.submit 'Create book' %>

<% end %>

app/views/books/show.html.erb
<main>
  <%= flash[:notice] %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/user', user: @user %>
        <%= render 'book', book: @book_new %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%=  image_tag @book.user.get_profile_image(100, 100) %><br>
                <%= link_to @user.name, user_path(@user.id) %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
                  <%= link_to "Destroy", book_path(@book), method: :delete,"data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<h1>Welcome to
<string><i class="fas fa-book"></i>Bookers</string>!</h1>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice]%>
<div>
  
<h1>welcome to
<string><i class="fas fa-book"></i>Bookers</string>!!</h1>
<p>In             
<string><i class="fas fa-book"></i>Bookers</string>,</p>
<p>you can share and exchnge your opinions,inpressions,and emotions</p>
<p>about various books</p>

<%= link_to "Log in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/7a964aeea7.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <p class="navbar-brand"><%= link_to 'Bookers', root_path %></p>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <i class="fas fa-home"></i>
              <%= link_to 'Home', user_path(current_user.id) %>
            </li>
            <li calss="nav-item">
              <i class="fas fa-users"></i>
              <%= link_to 'Users', users_path %>
            </li>
            <li calss="nav-item">
              <i class="fas fa-book-open"></i>
              <%= link_to 'Books', books_path %>
            </li>
            <li class="nav-item">
              <i class="fas fa-sign-out-alt"></i>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <i class="fas fa-home"></i>
              <%= link_to "Homes", root_path %>
            </li>
            <li class="nav-item">
              <i class="fas fa-link"></i>
              <%= link_to "About", about_path %>
            </li>
            <li class="nav-item">
              <i class="fas fa-user-plus"></i>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="nav-item">
              <i class="fas fa-sign-in-alt"></i>
              <%= link_to "Log in", new_user_session_path %>
            </li>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>
  <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>  
  </body>
</html>

app/views/users/_user.html.erb
<div>
 <h2>User info</h2>
 <%= image_tag user.get_profile_image(100,100) %>
 <h3 class="name">name</h3>
 <h3><%= user.name %></h3>
 <h3 class="user-text">introduction</h3>
 <h3><%= user.introduction %></h3>
 <%= link_to  edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
 <% end %>
</div>

app/views/users/edit.html.erb
<h2>Userinfo</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>

<label for = "inputName">Name</label>
<%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" %>

<labvel for = "inputImage">Image</labvel>
<%= f.file_field :profile_image, placeholder:"ファイル選択", accept: "image/*" %>


<level for = "inputintroduction">introduction</level>
<%= f.text_field :introduction, autofoucus: true, id:"inputintroduction", placeholder:"Introduction" %>
<%= f.submit "Update User" %>

<% end %>

app/views/users/index.html.erb
<main>
  <%= flash[:notice] %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'user', user: @user %>
        <%= render 'books/book', book: @book_new %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(100,100) %></td>
                <td><%= user.name %></td>
                <td><%= link_to 'Show', user_path(user.id) %> </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <%= flash[:notice] %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'user', user: @user %>
        <%= render 'books/book', book: @book_new %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>title</th>
              <th>opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do  %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>